export enum ActionStockTypeEnum {
    ORDER_SALE = 'ORDER_SALE' ,
    ORDER_CANCEL = 'ORDER_CANCEL' ,
    ORDER_REFUND = 'ORDER_REFUND' ,
    WAREHOUSE_TRANSFER = 'WAREHOUSE_TRANSFER',
    STOCK_IN = 'STOCK_IN',
    ADJUSTMENT = 'ADJUSTMENT'
}